server:
  port: 9090
  contextPath: /api
  request:
    maxBodySize: 20mb
solon:
  env: test
  alone: 1

solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss'
  dateAsTimeZone: 'GMT+8'
  nullAsWriteable: true

solon.logging.appender:
  console:
    level: DEBUG
    enable: true
  file:
    name: "logs/log"
    level: INFO
    enable: true #是否启用
    extension: ".log"
    maxFileSize: "10 MB"
    maxHistory: "7"
solon.logging.logger:
  "root":  #默认记录器配置
    level: INFO
  "com.example.solon":
    level: DEBUG

knife4j:
  enable: true
  basic:
    enable: true
    username: doc
    password: doc
  setting:
    enableOpenApi: true
    enableSwaggerModels: true
    enableFooter: false

mybatis:
  master:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    typeAliases:
      - "com.example.solon.template.dao.entity.*"
    mappers:
      - "classpath:mapper/*.xml"

    # tk mybatis的配置
    tk:
      mapper:
        style: camelhumpandlowercase
        safe-update: true
        safe-delete: true

pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false